{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "namespace-permission-manager.fullname" . }}
  labels:
    {{- include "namespace-permission-manager.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "namespace-permission-manager.selectorLabels" . | nindent 6 }}
  policyTypes:
  {{- if .Values.networkPolicy.ingress }}
    - Ingress
  {{- end }}
  {{- if .Values.networkPolicy.egress }}
    - Egress
  {{- end }}
  {{- with .Values.networkPolicy.ingress }}
  ingress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.networkPolicy.egress }}
  egress:
    {{- toYaml . | nindent 4 }}
  {{- end -}}
{{- end }}
